# Generated by Django 4.2.5 on 2023-09-09 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.TextField(max_length=100)),
                ('total_gredit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Year2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_code1', models.CharField(max_length=20)),
                ('sub_1', models.TextField(max_length=100)),
                ('marks_1', models.IntegerField()),
                ('grade_1', models.CharField(max_length=1)),
                ('sub_code2', models.CharField(max_length=20)),
                ('sub_2', models.TextField(max_length=100)),
                ('marks_2', models.IntegerField()),
                ('grade_2', models.CharField(max_length=1)),
                ('sub_code3', models.CharField(max_length=20)),
                ('sub_3', models.TextField(max_length=100)),
                ('marks_3', models.IntegerField()),
                ('grade_3', models.CharField(max_length=1)),
                ('sub_code4', models.CharField(max_length=20)),
                ('sub_4', models.TextField(max_length=100)),
                ('marks_4', models.IntegerField()),
                ('grade_4', models.CharField(max_length=1)),
                ('sub_code5', models.CharField(max_length=20)),
                ('sub_5', models.TextField(max_length=100)),
                ('marks_5', models.IntegerField()),
                ('grade_5', models.CharField(max_length=1)),
                ('sub_code6', models.CharField(max_length=20)),
                ('sub_6', models.TextField(max_length=100)),
                ('marks_6', models.IntegerField()),
                ('grade_6', models.CharField(max_length=1)),
                ('sub_code7', models.CharField(max_length=20)),
                ('sub_7', models.TextField(max_length=100)),
                ('marks_7', models.IntegerField()),
                ('grade_7', models.CharField(max_length=1)),
                ('remark', models.TextField(max_length=10)),
                ('semester', models.IntegerField()),
                ('student_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=20)),
                ('unit_name', models.TextField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='student.course')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.TextField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school', to='student.school')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depertment', to='student.department'),
        ),
    ]
