# Generated by Django 4.2.5 on 2023-09-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_course_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='period',
            field=models.CharField(choices=[('3', '3'), ('4', '4'), ('5', '5')], default='4'),
        ),
    ]
