# Generated by Django 4.2.5 on 2023-09-17 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_code1', models.CharField(max_length=20)),
                ('sub_1', models.CharField(max_length=200)),
                ('marks_1', models.IntegerField(blank=True, null=True)),
                ('grade_1', models.CharField(blank=True, max_length=1, null=True)),
                ('sub_code2', models.CharField(max_length=20)),
                ('sub_2', models.CharField(max_length=200)),
                ('marks_2', models.IntegerField(blank=True, null=True)),
                ('grade_2', models.CharField(blank=True, max_length=1, null=True)),
                ('sub_code3', models.CharField(max_length=20)),
                ('sub_3', models.CharField(max_length=200)),
                ('marks_3', models.IntegerField(blank=True, null=True)),
                ('grade_3', models.CharField(blank=True, max_length=1, null=True)),
                ('sub_code4', models.CharField(max_length=20)),
                ('sub_4', models.CharField(max_length=200)),
                ('marks_4', models.IntegerField(blank=True, null=True)),
                ('grade_4', models.CharField(blank=True, max_length=1, null=True)),
                ('sub_code5', models.CharField(max_length=20)),
                ('sub_5', models.CharField(max_length=200)),
                ('marks_5', models.IntegerField(blank=True, null=True)),
                ('grade_5', models.CharField(blank=True, max_length=1, null=True)),
                ('sub_code6', models.CharField(max_length=20)),
                ('sub_6', models.CharField(max_length=200)),
                ('marks_6', models.IntegerField(blank=True, null=True)),
                ('grade_6', models.CharField(blank=True, max_length=1, null=True)),
                ('sub_code7', models.CharField(max_length=20)),
                ('sub_7', models.CharField(max_length=200)),
                ('marks_7', models.IntegerField(blank=True, null=True)),
                ('grade_7', models.CharField(blank=True, max_length=1, null=True)),
                ('remark', models.CharField(max_length=200)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=20)),
                ('student_year', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('student_reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.department')),
            ],
        ),
        migrations.DeleteModel(
            name='Year2',
        ),
        migrations.AddField(
            model_name='cusomuser',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='student status'),
        ),
        migrations.AddField(
            model_name='cusomuser',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='teacher status'),
        ),
    ]
